# Webserver settings
webserver:
  # Port the webserver listens on
  port: 1337

# reCAPTCHA settings
recaptcha:
  # Public site key for your reCAPTCHA site. (reCAPTCHA site key)
  site-key: ""

# Discord settings
discord:
  # Guilds to provide endpoints for
  guilds:
    # id: Guild to create invites for. (Discord guild ID)
    # channel: Channel to create invite to. (Discord channel ID)
    # name: (optional) Override the name of the guild displayed on the website.
    #       Defaults to the guild's display name if blank or non-existent.
    # endpoint: (optional) Endpoint to attach and listen to. (HTTP location)
    #           Defaults to the name of the key.
    # domain: (optional) The (sub) domain this route applies to.
    #         Defaults to any unmatched domains.
    default:
      id: ""
      channel: ""
      endpoint: "/"
      domain: ""
